server:
  port: 8080

spring:
  application:
    name: guideon-backend

  # 1. 데이터베이스 설정
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/guideon}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  # 2. JPA
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100

  # 3. Redis 설정
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

# 4. 로깅 레벨 설정
logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.web: info