spring:
  application:
    name: guideon-be

  # 1. 데이터베이스 설정
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:guideondb}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # 2. JPA 설정
  jpa:
    hibernate:
      ddl-auto: update  #(운영은 validate)
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # 3. Redis 설정
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  # 4. 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# 로깅 레벨
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace